### ISSUE TITLE
Please add sub-folder support for the components part

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/elasticio.github.io#117]
In our recent discussion about component documentation, we concluded that a sub-folder structure would be useful in describing the components.

In particular, each component would have a folder with one default introduction file. Then more files are added they show as separate files in the sub-folder.
```
component_name
      |_____ introduction.md
      |_____ oauth_configuration.md
      |_____ use_cases.md
      |_____ etc ...
```

**Comment by khanzadyan** [comment]
@jhorbulyk and @juhrmacher following our discussion on 20th of March 2019

**Comment by drobiazko** [comment]
@khanzadyan here is a simple PR allowing you to define sub-folder for components. The sub-folder must contain `index.md` which could reference all the other pages.

https://github.com/elasticio/elasticio.github.io/pull/125
