### ISSUE TITLE
Describe limited/full workspaces

### ISSUE THREAD

**Issue by drobiazko** [elasticio/elasticio.github.io#120]
I'm not sure if this should be a single article or multiple articles. Here are the topics to cover:

* What are limited workspaces
  * periodic shutdown of flows
  * used for trial customers
* How to upgrade a `limited` workspace to a `full` workspace
* How to configure a tenant to use default workspace type (`limited` vs `full`)

**Comment by yarikos** [comment]
It worth to add a note about the `default workspace type` (`tenant.default_workspace_type`):
- is this variable required?
    - in other words – should I specify the value on new tenant create?
- if it's optional, what is the value for the newly created tenant?
    - in other words – if I create the new tenant, what `workspace.type` be by default for the tenant?
