### ISSUE TITLE
Roles management documentation

### ISSUE THREAD

**Issue by pnedelko** [elasticio/elasticio.github.io#124]
As a tenant admin I want to know how I can manage roles in my tenant.

-----

### Facts
1. Non-deletable roles
 - contract.owner
 - workspace.owner

2. It’s not possible to delete non-deletable roles
3. It’s not possible to change permissions of the non-deletable roles
4. It's not possible to submit non-uniq roles (duplicates of roles in the same scope)
5. It’s not possible to delete a role which is already assigned to some user
6. It’s not possible to delete a role which is used in contract.availableRoles

### Workflow
When a new tenant is created, it gets some predefined roles in each scope (contract & workspace). Contract Owner and Workspace Owner are mandatory and can't be deleted or modified. The other ones could be modified or deleted.

1. Get list of available [permissions](https://api.elastic.io/docs/v2/#get-the-list-of-available-permissions).
2. Get list of available [roles](https://api.elastic.io/docs/v2/#get-tenant's-roles)
3. Modify the payload of the previous response and [submit it](https://api.elastic.io/docs/v2/#update-tenant's-roles). If you want to delete a role, just remove it from the payload. If you want to add a role - add it to the payload.

**Comment by zubairov** [comment]
The important questions that I (as a reader) would be asking when reading this document:

- [ ] What will happen if I do something wrong?
- [ ] How can I rollback these changes?
- [ ] How this will affect existing users?
- [ ] How this will affect new users?
- [ ] How this will affect running integration flows?

**Comment by pnedelko** [comment]
@honeybadgeralex sorry, I didn't see that we have already the article: https://docs.elastic.io/guides/managing-user-roles-in-a-tenant.html.

Let's look at this issue as a collection of possible improvements.

**Comment by honeybadgeralex** [comment]
I am going to keep this issue alive until I get to rewriting docs on workflows.

**Comment by khanzadyan** [comment]
The article content is correct and ready. The screenshot will be updated later on. This will be a separate issue.
