### ISSUE TITLE
Can't find `ftp` connector

### ISSUE THREAD

**Issue by zubairov** [elasticio/elasticio.github.io#128]
For example:

![image](https://user-images.githubusercontent.com/56208/55611006-8464aa00-5784-11e9-8c2b-d77a0205fbf6.png)

Two options -> improve the description of the SFTP Connector or improve the 'fuzziness` of the search?

Thoughts?

**Comment by jhorbulyk** [comment]
Technically SFTP and FTP are different protocols so it is arguably logical that they don't match.

**Comment by slang-telekom** [comment]
They are more like synonyms nowadays from my point of view. I would expect to see SFTP when searching for FTP.

**Comment by juhrmacher** [comment]
hmm, just checked on github. If you look for FTP you will not find the SFTP repo.

Nevertheless, I would suggest improving the 'fuzziness` of the search?

Will it be confusing if we search for *FTP* ???

**Comment by jhorbulyk** [comment]
> Two options -> improve the description of the SFTP Connector or improve the 'fuzziness` of the search?

My vote is improve the description of the SFTP connector that generic fuzziness tuning as I feel this is a pretty niche case.

**Comment by khanzadyan** [comment]
This problem is fixed. It was connected with the length of searched fields and the typo tolerance setup in Algolia. The default value was set to 4 characters. I  decreased it to 3 and the `ftp` search shows the `sftp` component as well.
