### ISSUE TITLE
Usability bug in search field

### ISSUE THREAD

**Issue by zubairov** [elasticio/elasticio.github.io#129]
When selecting one of the found alternatives browser do not navigates to the selected search:

![screencast 2019-04-05 09-32-54](https://user-images.githubusercontent.com/56208/55611509-01dcea00-5786-11e9-90da-ed36fe348ba5.gif)

Expected behavior is that once clicking on the search result, user will be navigated to it. Must be some CSS / Styling issue

**Comment by zubairov** [comment]
@drobiazko any progress here?

**Comment by khanzadyan** [comment]
Corrected the style to fix this.
