### ISSUE TITLE
Update Quota page documentation right way

### ISSUE THREAD

**Issue by Glico21** [elasticio/elasticio.github.io#1330]
We noticed that we have one page on the main documentation resource that describes the quota. But this page needs to be reworked because we have several different ways for quota counting that are not described in detail on any page.

The page that need to be reworked: https://docs.elastic.io/getting-started/quota-overview.html
Additional information can be grabbed from the [Notion page](https://www.notion.so/elasticio/quota-service-a32fe8bf576a4e65b3f83c2749a099fe)  and [op-prem docs](https://on-prem.elastic.io/admin/quotas/flow-count-limit)

**Comment by Glico21** [comment]
It was decided to create a new article in the Integrator Guide -> Contract management section that describes in detail the features of `LimitRecords`. The old article remains unchanged for the time being.

**Comment by Glico21** [comment]
https://github.com/elasticio/elasticio.github.io/pull/1335

**Comment by andrewreshitko** [comment]
completed
