### ISSUE TITLE
Fix wording on the JDBC Component documentation page

### ISSUE THREAD

**Issue by vadim-eio** [elasticio/elasticio.github.io#1331]
Please fix wording on the JDBC Component documentation page: https://docs.elastic.io/components/jdbc/index.html

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--542335075497b7fb2ad5352d430ad006a5fbcded/jdbc_doc.png)

Duplicate words "works with the" should be removed.

**Comment by Glico21** [comment]
Part of the huge [PR](https://github.com/elasticio/elasticio.github.io/pull/1360)
