### ISSUE TITLE
Local agent description for UI

### ISSUE THREAD

**Issue by honeybadgeralex** [elasticio/elasticio.github.io#179]

**Comment by honeybadgeralex** [comment]
**Disclaimer:** 
A Local Agent allows you to create a secure on-premise database for the Platform, restricting any external access to it. It is intended for companies that work with clients' personal data, or just have strict data security policies. For example:

- Government institutions, military, law enforcement
- Healthcare and insurance 
- Banks, telecommunication companies, etc.

Local Agent requires extensive on-premise compute and storage resources. Before requesting a Local Agent, please ensure that your task requires it, and that you meet its hardware/software requirements.

**Comment by honeybadgeralex** [comment]
Please assign to someone who can put it into the UI

**Comment by zubairov** [comment]
@drobiazko @honeybadgeralex 

I think UI would be very beneficial but most essential part of the local agent documentation is actually documenting what it is, what's inside, which networking topology it expects and what resources (RAM/CPU) it needs.

You can see this samples from our competitors:

https://docs.workato.com/on-prem.html

https://docs.workato.com/on-prem/setup.html

https://help.boomi.com/bundle/integration/page/c-atm-Atom_setup_f7dedf01-31c1-4642-824b-9c76d5d0bf8e.html

please also consider look into these issues:

https://github.com/elasticio/elasticio.github.io/issues?q=is%3Aissue+is%3Aopen+local+author%3Akhanzadyan

**Comment by khanzadyan** [comment]
@zubairov I still think we need this description on the local agent page in our platform UI. The absence of this or any description is creating unnecessary overhead for the support and operations. Documenting it is also important - no argument there.

**Comment by khanzadyan** [comment]
Issue moved to [elasticio/docs #16](https://github.com/elasticio/docs/issues/16) via [**ZenHub**](https://www.zenhub.com/)
