### ISSUE TITLE
Port Over Snapshot documentation from support.elastic.io

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio.github.io#190]
Currently, on support.elastic.io, there is a three part article series about the platform's snapshot feature: https://support.elastic.io/support/solutions/folders/14000112651 Currently, on docs.elastic.io there is no documentation on the platform's snapshot feature.  This should be solved, ideally by moving over information from the old documentation source.

![Screenshot from 2019-07-15 12-58-58](https://user-images.githubusercontent.com/5710732/61220787-585bac00-a717-11e9-9d3c-20e73d6cd770.png)

**Comment by jhorbulyk** [comment]
Information that ideally would be covered in the new documentation:
* How to redo a polling interval by
  * Stopping the flow
  * Reseting the snapshot
  * Changing the polling start time
  * Publishing the flow
  * Starting the flow 
* Communicate that by reaching out to support, they can set the snapshot to any value requested.

**Comment by khanzadyan** [comment]
This issue is done. We have two different documents about snapshots. We will add more in due course.
