### ISSUE TITLE
Document how to recover a flow from a queue overflow state

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio.github.io#208]
![Screenshot from 2019-08-12 09-22-51](https://user-images.githubusercontent.com/5710732/62850371-f5900d00-bce2-11e9-856a-4195727fa62e.png)

When a user recieves this email, they need to do the following:
* Stop the flow with the API
* Start the flow

These instructions should be recorded.

**Comment by khanzadyan** [comment]
We are not suspending the flows based on queue overflow state. It is managed by the dynamic flow control.
