### ISSUE TITLE
Stub articles in our documentation do not reflect highly on our company

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio.github.io#209]
## Steps to Reproduce:
1. Look for information on webhooks in our documenation at docs.elastic.io
1. The first result returned is `Webhook Component`
![Screenshot from 2019-08-13 15-01-30](https://user-images.githubusercontent.com/5710732/62943686-56027580-bddb-11e9-9940-b6cca1741286.png)
1. Visit the article.

## Expected results:
Some usable information that reflects on the professionalism and seriousness of elasticio as a company.

## Actual results
You are rendered something that does not reflect on elasticio as company.
![Screenshot from 2019-08-13 15-01-53](https://user-images.githubusercontent.com/5710732/62943864-b4c7ef00-bddb-11e9-8209-7afa0c05bb55.png)

**Comment by khanzadyan** [comment]
@jhorbulyk The process has begun on cleaning and correcting the situation. The example above is already addressed. If you have some other pages in your mind as well please submit them here as well.

**Comment by jhorbulyk** [comment]
I don't have any pages in mind at the moment.  I can close this issue since the most egregious instances have been fixed.
