### ISSUE TITLE
Add documentation on the issue that arrays can not be rendered in the Integration mode

### ISSUE THREAD

**Issue by A3a3e1** [elasticio/elasticio.github.io#219]

**Comment by jhorbulyk** [comment]
The limitation only occurs when the in metadata has an array where elements of the array must be objects.  The limiation does not occur when the in metadata has an array where elements of the array are strings, numbers or other primative types.

**Comment by khanzadyan** [comment]
@jhorbulyk I suppose we could close this ticket? A new document about array to array mapping is in progres.
