### ISSUE TITLE
Update screenshots with new navigation

### ISSUE THREAD

**Issue by drobiazko** [elasticio/elasticio.github.io#220]
We have some pages showing the old navigation. Here are few examples:

- https://docs.elastic.io/getting-started/tour.html
- https://docs.elastic.io/guides/ssh-keys.html

Please go through all the pages and update screenshots.

**Comment by khanzadyan** [comment]
This is done. We have removed the tour page since it was showing completely confusing and wrong information. The SSH key page has all updated screenshots.
