### ISSUE TITLE
Broken links on docs

### ISSUE THREAD

**Issue by hannah-bulmer** [elasticio/elasticio.github.io#237]
Some of the links on the docs pages point to 404 pages. They are highlighted in images below.
***

In [Getting Started: First Flow](https://docs.elastic.io/getting-started/first-flow),
![image](https://user-images.githubusercontent.com/35310862/64770281-2adf8300-d54d-11e9-9c54-fa4823e54319.png)
![image](https://user-images.githubusercontent.com/35310862/64770302-38950880-d54d-11e9-8b83-7f7f0f8af1b1.png)
***
In [Data Sample Overview](https://docs.elastic.io/getting-started/data-sample-overview.html)
- these are also anchor links that do not work
![image](https://user-images.githubusercontent.com/35310862/64770433-77c35980-d54d-11e9-82ba-d3d6bb5f181f.png)
***
In [Realtime Flows](https://docs.elastic.io/guides/realtime-flows.html)
![image](https://user-images.githubusercontent.com/35310862/64770527-a2151700-d54d-11e9-91e1-cd83b8f71ab6.png)

AR: links do not open the information they should
ER: links point to the correct pages

**Comment by khanzadyan** [comment]
Broken links fixed. Thanks @hannah-bulmer
