### ISSUE TITLE
Document quota system

### ISSUE THREAD

**Issue by pnedelko** [elasticio/elasticio.github.io#244]
Please document the quota system:
- How and who is able to set the quota?
- Quota UI (e.g. what units are used and how they are being calculated)
- Quota and usage API

**Comment by pnedelko** [comment]
![image](https://user-images.githubusercontent.com/2523461/66645855-cdf6eb80-ec24-11e9-83cf-12e47778856a.png)

**Comment by khanzadyan** [comment]
Quota explanation is done. We will add more information soon.

**Comment by khanzadyan** [comment]
This is done and published.
