### ISSUE TITLE
Describe rebound feature

### ISSUE THREAD

**Issue by umkaline** [elasticio/elasticio.github.io#271]
Add article(s) about rebound platform functionality.

Source of information:
https://support.elastic.io/support/solutions/folders/14000109788

**Comment by khanzadyan** [comment]
We transferred the rebound feature documentation from the old site to the new one. 

* https://docs.elastic.io/getting-started/rebound.html
* https://docs.elastic.io/guides/how-to-cause-or-emit-a-rebound.html
