### ISSUE TITLE
There should be some documentation on "Developer Mode"

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio.github.io#272]
![ksnip_20190930$](https://user-images.githubusercontent.com/5710732/65878240-d9792580-e38d-11e9-8eff-9f3f715eee1a.png)

Some explaination of:
* What it is
* How to use it
* Why one would use it instead of "Intergrator Mode"

**Comment by jhorbulyk** [comment]
What is currently available at support.elastic.io: https://support.elastic.io/support/solutions/articles/14000076868-new-features-of-our-ui-november-2017#dev-mode

**Comment by khanzadyan** [comment]
@jhorbulyk this is a good idea. The old document should disappear and a new one must be present. I'm just wondering if the developer mode documentation would somehow be short-lived since the new mapper interface might influence the whole presentation of it.

**Comment by honeybadgeralex** [comment]
Sooooo, after some research I have come to a conclusion that we already have some of that info. The issue is more than half a year old, so, figures.
