### ISSUE TITLE
It's not possible to scroll down on the sidebar for the documentation page

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio.github.io#294]
See the .GIF
![Documentation Side Bar](https://user-images.githubusercontent.com/5710732/66566719-ee13a580-eb65-11e9-9e3f-d3e537afcada.gif)

**Comment by khanzadyan** [comment]
Thanks for reporting this @jhorbulyk . The issue was copied into our internal board.

**Comment by khanzadyan** [comment]
@jhorbulyk the menu was removed since it was rarely used and was more complicated to fix.
