### ISSUE TITLE
The JSON Test Tool should be documented

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio.github.io#341]
The JSON Test Tool at `https://app.elastic.io/c/CONTRACT_ID/try-component-metadata` should be documented.

**Comment by khanzadyan** [comment]
@jhorbulyk do we have this functionality right now? I can't seem to find this.

**Comment by jhorbulyk** [comment]
Try https://app.elastic.io/c/5b62c91afd98ea00112d53f6/try-component-metadata

**Comment by khanzadyan** [comment]
Issue moved to [elasticio/docs #311](https://github.com/elasticio/docs/issues/311) via [**ZenHub**](https://www.zenhub.com/)
