### ISSUE TITLE
Describe the Local Agent

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/elasticio.github.io#41]
Draft a document or series of documents to describe the Local Agents. At the moment we have only one document announcing the Local Agents: https://support.elastic.io/support/solutions/articles/14000076461-announcing-the-local-agent-

This document shows how to work with the local agent, but the bigger questions are not answered. For example, the following questions still need answers:

* What is a Local Agent?
* Why would you use the Local Agent?
* What are the typical use cases of Local Agents?

**Comment by jhorbulyk** [comment]
In particular add:

> The typical use cases are:
> * The agent can sit behind a firewall
> * An execution step can be fixed to an IP
> * The distance between the data and the code extracting the data is reduced.

**Comment by khanzadyan** [comment]
Issue moved to [elasticio/docs #13](https://github.com/elasticio/docs/issues/13) via [**ZenHub**](https://www.zenhub.com/)
