### ISSUE TITLE
Describe how to build an integration

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio.github.io#42]
One of the exercises I recently gave out in a training was:

> # Build a smart flow between two systems
> Create flows to map New and Updated Dynamics 365 Contacts to SugarCRM contacts.  Use the S2/Key-Value component to link IDs.

The written answer key would likely be useful information to add to our documentation.  

(Without S2/Key-Value there is the posibility to also describe how to do this in the case where the id linking is stored in the receiving system.)

**Comment by khanzadyan** [comment]
@jhorbulyk can you please give a bit more information with examples and screenshots so that I can investigate it?

**Comment by jhorbulyk** [comment]
@khanzadyan Additional information was provided offline.
