### ISSUE TITLE
"Search" field is became unfocused and minimized after delete search input.

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/elasticio.github.io#45]
Description: Search field became unfocused after delete search input from field.

STR:
1. Go to: https://docs.elastic.io.
2. Select "Search" field.
3. Type: "http".
4.  Delete all from "Search" field.

AR: Search field is became unfocused and collapsed after delete search input.

![peek 2018-06-04 13-49](https://user-images.githubusercontent.com/32069340/40913732-2ba2fc44-67fe-11e8-8c52-cf136562d828.gif)

ER: Search field is remaning focused and extended after delete search input.

**Comment by khanzadyan** [comment]
Corrected this bug. Now the focus is not lost when the field is cleared.
