### ISSUE TITLE
Add documentation on how to fetch all the relevant information required to expedite a support request

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio.github.io#46]
Things include:
* Including orgId, flow Id, component ID, execution ID, credentials ID etc.
* Steps to reproduce
* In the event of failed request to frontent, the request and the reply
* Logs, stacktrace, incoming data in text from
* Screenshots/animated gifs
* Expected behavior vs actual behavior
* Whether a work around is required or whether this is just a request for a long term fix

etc.

**Comment by khanzadyan** [comment]
Very good point @jhorbulyk - this process needs to be documented. However, I'm not sure where this kind of document needs to be presented. The documentation as it stands is done for white-labelling. Providing such kind of document would not fit with the idea.

**Comment by jhorbulyk** [comment]
@drobiazko what are your thoughts?  It seems like this documentation could be whitelabled.  If a customer didn't want this particular piece or section, they could remove it in their fork.

**Comment by drobiazko** [comment]
@jhorbulyk I tend to agree with @khanzadyan as the docs should be usable for white-label partners without any modifications to its content. It's very difficult to find out what you must delete from the docs before you start using it. It also goes against our advise 5. in the readme of the docs. Changing the contents will result in merge conflicts. Maybe this kind of documentation should be placed in the support system, e.g. Freshdesk, Zendesk, etc. and not in the product docs.
