### ISSUE TITLE
Add the text for empty state on the treads execution page

### ISSUE THREAD

**Issue by HannaTrotsenko** [elasticio/elasticio.github.io#520]
# Internal Issue/Enhancement

## Description

We have a 2 different cases for an empty state
1. User hasn't any threads because no executions yet 
2. There are no threads matching filters

But the text should be universal for both

## Definition of Done

- [ ] Add the text for empty state on the treads execution page according to the design https://app.zeplin.io/project/5d370f89e139d2414019bd64/screen/5e13217acaa0d698e14a5232

**Comment by honeybadgeralex** [comment]
No Executions to display. Either there are no active Executions, or none of them match the selected filters. Also, make sure you have restarted your realtime Flows before accessing their Executions, because they might not appear in the list otherwise.

**Comment by khanzadyan** [comment]
@HannaTrotsenko and @honeybadgeralex is this done already?
