### ISSUE TITLE
Platform invitation error text

### ISSUE THREAD

**Issue by HannaTrotsenko** [elasticio/elasticio.github.io#521]
- Invite new member from Workspace management page: 
If user types an email of already existing user in the contract -> error message
An error message text needed

- Invite new member from Workspace management page: 
If the user entered an email which was already invited into the contract, but the invitation was not accepted yet - we allow to use this form, but we check, if the invitation settings differ from the ones in the DB. If they differ, we show the difference and ask the user to confirm. 
A confirm text needed

- The same as previous case, but we check the differences of workspace invitations as well.

- Invite new member from Contract management page: 
If the user types an email of already existing contract member, we show a validation error and still don't enable the "Send Invite" button.
A validation error text needed

**Comment by honeybadgeralex** [comment]
1. *Error message:* The user you are trying to invite is already a member of this Contract. 

2. *Confirmation text*: There is a pending Contract invitation to this user, but the invitation settings are different. Please confirm new settings to resend the invitation. 

3. *Confirmation text*: There is a pending Contract/Workspace invitation to this user, but the invitation settings are different. Please confirm new settings to resend the invitation. 

4. *Validation error text*: Already a member. Please enter another address.

All Lorem Ipsum in the next comment

**Comment by khanzadyan** [comment]
@HannaTrotsenko and @honeybadgeralex have we done this?
