### ISSUE TITLE
Broken links are existing in documentation

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/elasticio.github.io#54]
Description: Broken links are existing in documentation
Tested with [brokenlinkcheck.com](http://www.brokenlinkcheck.com) - 

STR:
1. Open https://docs.elastic.io.
2. Click on highlighted that are highlighted on screenshots.
![docs1](https://user-images.githubusercontent.com/36419533/42213697-33e77756-7ec2-11e8-8e37-64493db03ff8.png)

![docs2](https://user-images.githubusercontent.com/36419533/42213700-36b823cc-7ec2-11e8-80c2-a41a4816852c.png)

![docs3](https://user-images.githubusercontent.com/36419533/42213706-3941d6c4-7ec2-11e8-818c-c4b7f0c81bf3.png)

![docs4](https://user-images.githubusercontent.com/36419533/42214047-12e3f15a-7ec3-11e8-9685-4fd1e72f93dc.png)

AR: 6 links are broken  - 404 code.

ER: All links follows to the necessary pages/

**Comment by khanzadyan** [comment]
@stas-fomenko corrected, deployed.
