### ISSUE TITLE
All external links opens in the same tab but not in new one

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/elasticio.github.io#55]
Description: All external links opens in the same tab but not in new one

STR:
1. Open https://docs.elastic.io
2. Find external link and click on it. (for example https://docs.elastic.io/getting-started/webhooks-flow.html -> "Basic Access Authentication" link on page bottom)

AR: All external links opens in the same tab but not in new one

ER: All external links opens in new tab.

**Comment by khanzadyan** [comment]
@drobiazko I found this resource: http://fraktar.com/markdown-redcarpet-target-blank/ could be useful for us to address this issue.

**Comment by khanzadyan** [comment]
The fix is online and working. Closing down the issue.
