### ISSUE TITLE
Create new TOC Pattern for component documentation

### ISSUE THREAD

**Issue by zubairov** [elasticio/elasticio.github.io#56]
As discussed in https://github.com/elasticio/platform/issues/379#issuecomment-402686107 we need a new TOC Pattern for component documentation.

See https://github.com/elasticio/platform/issues/379 for more information

**Comment by zubairov** [comment]
@khanzadyan thoughts? TBH I'm not sure what is the TOC Pattern?

**Comment by drobiazko** [comment]
How about this?

1. Short introduction: what this component is about? what target system is it for? bla bla bla
2. How to find the component in the designer
3. How to push the component as private component, if it not available in the designer but is open source
4. How to get the credentials in the target system
5. How to create a simple flow using a trigger, if available
6. How to create a simple flow using an action, if available
7. Known issues, if available

**Comment by jhorbulyk** [comment]
@stas-fomenko [started something along the same set of ideas.](https://docs.google.com/document/d/1d4BDV5JQKr-Z5v8-vsD234sbdL_zvDimx1Un42mMsPY/edit?usp=sharing)

I have [this overly complicated sheet where I attempted to identify all the information that one could possibly need to know about a component.](https://docs.google.com/spreadsheets/d/1T6KUxSKJPd9Kct2uRcMbe5uhWr4Zic1mFFys_rHoSWc/edit#gid=0)

Does it make sense to compile a simple list of topics that could exist in a component readme and then do a :+1: or :-1: to see if there is a shared understanding of what needs to be documented?

**Comment by zubairov** [comment]
@drobiazko @khanzadyan not sure I understood you correctly, shall we repeat #2 and #3 for each component?

**Comment by khanzadyan** [comment]
@zubairov I don't think we need to do that. We just need to include this as subsection and point it to the right documentation.

**Comment by zubairov** [comment]
@khanzadyan would you be able to provide a first "lorem ipsum" sample for @elasticio/ps to copy and fill?
