### ISSUE TITLE
update the rest-api component documentation

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/elasticio.github.io#65]
After the recent release, the REST API component gained new functionality and some of the limitations are gone.

Review the documentation and make the changes.

**Comment by khanzadyan** [comment]
@stas-fomenko can you please check and let me know what needs to be changed and added in the REST API documentation which is here: https://docs.elastic.io/integrator-guide/rest-api-component 

Just comment it here so that I can start working on it.

**Comment by stas-fomenko** [comment]
@tiUpdates:
- Attachments support (https://github.com/elasticio/rest-api-component/issues/30)
- Redirects (https://github.com/elasticio/rest-api-component/issues/40)
- Improved error handling (https://github.com/elasticio/rest-api-component/issues/41)

**Comment by stas-fomenko** [comment]
@khanzadyan

**Comment by stas-fomenko** [comment]
@khanzadyan 
Latest updates:
- Attachments support (https://github.com/elasticio/rest-api-component/issues/30)
- Redirects (https://github.com/elasticio/rest-api-component/issues/40)
- Improved error handling (https://github.com/elasticio/rest-api-component/issues/41)

**Comment by khanzadyan** [comment]
Thanks @stas-fomenko, I will proceed with the update using this information.

**Comment by khanzadyan** [comment]
Update on 18th of September 2019: the component document was updated https://docs.elastic.io/components/rest-api-component.html
