### ISSUE TITLE
What is a sample?

### ISSUE THREAD

**Issue by drobiazko** [elasticio/elasticio.github.io#79]
Collection: Getting Started
Section: Basic Concepts
Article: What is a sample?

We want to introduce the term `Sample` and explain why we need it. Because we are going to talk about mapping here, let's also reference the [mapping guide](https://github.com/elasticio/elasticio.github.io/blob/master/_guides/mapping-data.md) in this article. Also the pages [Creating your first integration flow](https://github.com/elasticio/elasticio.github.io/blob/master/_getting-started/first-flow.md)  and [ Creating a webhook flow](https://github.com/elasticio/elasticio.github.io/blob/master/_getting-started/webhooks-flow.md) should refer to this page when mentioning Samples.

**Comment by al3xive** [comment]
https://github.com/elasticio/elasticio.github.io/pull/105
