### ISSUE TITLE
Image Preview & Image Border Shadow features add.

### ISSUE THREAD

**Issue by al3xive** [elasticio/elasticio.github.io#81]
It'd be great to be able to have such functionality as Image Preview (something like JS Pretty Photo library to be able to expand the necessary image) and Image Border Shadow for the screenshots in our official documentation. Please check the examples below. 

You may also check one of my Documentations I made for a previous project. 
http://williamson.themerex.net/doc/#homepage_settings_page_templates

Screenshot - http://prntscr.com/lx2ggo
jQuery prettyPhoto Library - https://github.com/scaron/prettyphoto

Image Borders - http://prntscr.com/lx2htl
So the screenshots taken on white BG will be more visible.

**Comment by khanzadyan** [comment]
@al3xive and @drobiazko this could be a solution: https://github.com/appfoundry/jekyll-lightbox
