### ISSUE TITLE
Article on how to install/update platform using ksonnet

### ISSUE THREAD

**Issue by drobiazko** [elasticio/elasticio.github.io#91]
Collection: How-to Guides
Section: On-prem
Content:

* introduction: brief intro into ksonnet, why we need it, how does it relate to e.io
* how to install e.io platform on my hardware using ksonnet
* how to update the running platform to a new version using ksonnet
* elaborate on deployment descriptor parameters

**Comment by khanzadyan** [comment]
Issue moved to [elasticio/elasticio-operations-docs #16](https://github.com/elasticio/elasticio-operations-docs/issues/16) via [**ZenHub**](https://www.zenhub.com/)
