### ISSUE TITLE
White-labeling using the {{site.data.tenant.name}} placeholder.

### ISSUE THREAD

**Issue by al3xive** [elasticio/elasticio.github.io#93]
Please provide the list of values we are allowed to replace/white-label with the {{site.data.tenant.name}} placeholder. Also, please advice on how do we handle the case with the values that cannot be replaced (or not allowed to). 

For example, how do we go about dealing with the specific commands like this one

`ks generate elastic.io.gendry gendry`

**Comment by khanzadyan** [comment]
This issue is outdated and there is no point to keep it open.
