### ISSUE TITLE
Weird 'Search' field behavior when typing the next in.

### ISSUE THREAD

**Issue by al3xive** [elasticio/elasticio.github.io#98]
Hi guys!

Here's the thing. As soon as you start typing text/keyword into the search field and suddenly realize that you found what you were looking for or you just changed your mind and don't want to proceed for some reason. Usually what you'd do is click somewhere on the screen to make the search field disappear, or you hit the 'Escape' button to get rid of the search results. This is a common scenario for such kind of cases. The problem is that nothing happens. The dropdown with suggested search results stays as it is and don't go anywhere don't matter what you do. So, you have to refresh the page. That's the only way out.

See the screenshots below:

http://prntscr.com/mgts6i

http://prntscr.com/mgtsey

**Comment by khanzadyan** [comment]
Functionality is improved. Search field behaves better.
